image: Ubuntu1804  # образ для сборки

stack: node 18  # окружение

branches:
  only:
    - main  # ветка git

cache: node_modules  # кеширование

install:
  - sudo apt-get update && sudo apt-get install curl
  - curl -sL https://deb.nodesource.com/setup_current.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования

deploy_script:  # скрипт развёртывания


